version: '3.4'

services:  
  unit-tests:
    image: ${DOCKER_REGISTRY:-snakesandladders}/unittests:${TAG:-latest}
    build:
      context: .
      dockerfile: tests/SnakesAndLadders.UnitTests/Dockerfile


