name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
      
    - name: Unit tests
      run: docker-compose -f docker-compose-unit-tests.yml up --build unit-tests && docker-compose -f docker-compose-unit-tests.yml run unit-tests
